### PR TITLE
Enhancement/8

### PR DESCRIPTION
**Pull request by manmadeharp**
style to identify currentpage is open by making nav of selected page bold

### CODE REVIEW

**Comment by manmadeharp** [comment]
sorry I accidentally pushed the documentation #21 with this issue as well is that ok

**Comment by manmadeharp** [comment]
also how do I resolve the conflicts?

**Review by andyekomat — APPROVED** [review]
good to go

**Review by nmunro — CHANGES_REQUESTED** [review]
It would have been more efficient to write a single css class and apply the class instead of three different id rules that all do the same thing. Just a way to make it more efficient.

**Review by nmunro — APPROVED** [review]

**Review by andyekomat — APPROVED** [review]
good to go

**Pull request merged**
